exp_type: toptagging_scalar
exp_name: topt_debug

data:
 data_dir : /global/cfs/cdirs/m3246/twamorka/lgatr/lorentz-gatr/h1_preprocess/
 dataset: combinedh1_withscalars_100particles_2p5M

defaults:
 - default_tagging
